### ISSUE TITLE
Error setting up entry IPX800 for ipx800v4 3.8.3

### ISSUE THREAD

**Issue by aelttil** [Aohzan/ipx800#59]
Hello,

The extension is showing a configuration error in HA. This seems to have appeared since my upgrade to 3.8.3.
Are you aware of this issue?

Best regards,
Alexandre.

## ipx800v4 version:
 *  3.8.3
 * 
## HA version 
* Core2024.10.4
* Supervisor2024.10.3
* Operating System13.2
* Interface utilisateur20241002.3

Error message:

```
2024-11-06 11:31:09.803 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry IPX800 for ipx800v4
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ipx800v4/__init__.py", line 161, in async_setup_entry
    await check_connection()
  File "/config/custom_components/ipx800v4/__init__.py", line 157, in check_connection
    if not await ipx.ping():
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pypx800/ipx800.py", line 131, in ping
    result = await self.request_api({"Get": "R"})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pypx800/ipx800.py", line 60, in request_api
    with async_timeout.timeout(self._request_timeout):
TypeError: 'Timeout' object does not support the context manager protocol

```

**Comment by aelttil** [comment]
The bug is fixed in 3.8.4.
Thank you for the quick fix!
